apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: first-project
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: first-project
  spec:
    selector:
      app: first-project
    ports:
      - protocol: TCP
        port: 8000
        targetPort: 8000
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: first-project
  spec:
    to:
      kind: Service
      name: first-project
    port:
      targetPort: 8000
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: first-project
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: first-project
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: first-project
      spec:
        containers:
        - name: first-project
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
parameters:
- description: Image name
  name: IMAGE
  value: quay.io/rh-ee-ffeghali/first-project
- description: Image tag
  name: IMAGE_TAG
  value: "multi-build"
  required: true